### DISCUSSION TITLE
Why is jellyseerr showing titles from private library it shouldn't have access too.

### DISCUSSION THREAD

**Discussion by lazie0402** [seerr-team/seerr#1637] [Q&A] [answered]
I'm running both overseerr and jellyseerr to see with one I like more and I've noticed that jellyseer is show titles in the recently added from a library it's not supposed to be monitoring. I've checked radarr and the files are in the correct folders and plex show them in the correct libraries the settings between both jellyseerr and overseer are identical so I'm not sure why these titles are showing up. I manually removed them and when the scan job ran, they were readded. Jellyseerr is running in docker on a ubuntu server instance host in Proxmox. Following is my docker compose file along with a screenshot showing the library in question turned off in settings.

```
services: 
 overseerr:
     image: lscr.io/linuxserver/overseerr:latest
     container_name: overseerr
     network_mode: user_default
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=America/Chicago
     volumes:
       - /home/user/config/overseerr:/config # config file local host
     restart: unless-stopped
     ports:
       - 5055:5055
 cloudflared:
     image: cloudflare/cloudflared:latest
     container_name: cloudflared
     restart: unless-stopped
     command: tunnel run
     environment: 
       - TUNNEL_TOKEN=My_Token
 #___________Jellyseerr____________
 jellyseerr:
     image: ghcr.io/fallenbagel/jellyseerr:latest
     container_name: jellyseerr
        network_mode: user_default
     environment:
       - LOG_LEVEL=debug
       - TZ=America/Chicago
       - PORT=5555 #optional
     ports:
       - 5555:5555
     volumes:
       - /home/user/config/jellyseerr/config:/app/config # config file local host
     restart: unless-stopped  
  #_______________Watchtower____________
 watchtower:
     image: containrrr/watchtower
     container_name: watchtower
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
     environment:
      TZ: America/Chicago
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 43200 # checks for updates every 12 hours
     restart: unless-stopped 
```
![jelly](https://github.com/user-attachments/assets/ac5e75e8-e0cd-49cb-b264-7900556c5c82)
