### ISSUE TITLE
Jellyseerr API api/v1/request/count incorrectly shows "0 available media"

### ISSUE THREAD

**Issue by KevsterAmp** [seerr-team/seerr#1735]
### Description

Running 
```bash
curl -L -k -H "X-Api-Key:<apikey>" http://<jellyseerr.ip>/api/v1/request/count
```
returns:
```json
{"total":6,"movie":6,"tv":0,"pending":0,"approved":1,"declined":0,"processing":1,"available":0}
```

But my jellyseerr clearly shows a couple of available media in the webUI

Running via docker compose on Ubuntu Server 24.04
```yaml
---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ={{TZ}}
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ~/homelab/jellyseerr/config:/app/config
    restart: unless-stopped
```

### Version

2.7.0

### Steps to Reproduce

1. make a media available in jellyseer
2. access /api/v1/request/count
3. JSON output contains "available": 0

### Screenshots

<img width="1437" alt="Image" src="https://github.com/user-attachments/assets/c1587ff8-94d8-4eb0-b31c-6b23f879f6f7" />

### Logs

```shell

```

### Platform

desktop

### Database

SQLite (default)

### Device

ASUS X455LF 1.0

### Operating System

Ubuntu 24.04.2 LTS x86_64

### Browser

Edge

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct
