### ISSUE TITLE
commitTag of $GIT_SHA in /api/v1/status for Docker image

### ISSUE THREAD

**Issue by TomatoCo** [seerr-team/seerr#707]
### Description

While I was messing around with the app I noticed that, for the docker image at least, the `/api/v1/status` endpoint returns this json: `{"version":"1.7.0","commitTag":"$GIT_SHA","updateAvailable":false,"commitsBehind":0,"restartRequired":false}`

That's probably not right. Is just my install being weird?

### Version

1.7.0

### Steps to Reproduce

Start a Jellyseerr service with a docker compose approximately like this:

```
services:
  jellyseer:
    image: fallenbagel/jellyseerr:1.7.0
    container_name: jellyseerr
    hostname: jellyseerr
    user: 1000:1000
    environment:
      - TZ=Etc/UTC
    ports:
      - 5055:5055
    volumes:
      - ./config:/app/config
    restart: unless-stopped
```

### Platform

desktop

### Device

Intel/nVidia Desktop

### Operating System

W11

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct
